#!/usr/bin/env bun
/**
 * Generates a TypeScript file with available models and modes for each agent.
 * Run with: bun run scripts/generate-models.ts
 */
import { writeFileSync } from "node:fs";

const AGENTS = ["claude", "codex"] as const;
const SERVER_URL = process.env.SERVER_URL || "http://localhost:3456";

type AgentType = (typeof AGENTS)[number];

interface ModelInfo {
  modelId: string;
  name: string;
  description?: string;
}

interface ModeInfo {
  id: string;
  name: string;
  description?: string;
}

interface SessionResponse {
  sessionId: string;
  models?: {
    availableModels: ModelInfo[];
    currentModelId: string;
  };
  modes?: {
    availableModes: ModeInfo[];
    currentModeId: string;
  };
}

async function getAgentInfo(agent: AgentType): Promise<SessionResponse> {
  // Create session
  const createRes = await fetch(`${SERVER_URL}/sessions`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ agent }),
  });

  if (!createRes.ok) {
    throw new Error(
      `Failed to create ${agent} session: ${createRes.statusText}`
    );
  }

  const session: SessionResponse = await createRes.json();

  // Clean up session
  await fetch(`${SERVER_URL}/sessions/${session.sessionId}`, {
    method: "DELETE",
  });

  return session;
}

async function main() {
  console.log("Fetching agent info...\n");

  const agentData = {} as Record<AgentType, SessionResponse>;

  for (const agent of AGENTS) {
    console.log(`  ${agent}...`);
    try {
      agentData[agent] = await getAgentInfo(agent);
      console.log(
        `    ✓ ${agentData[agent].models?.availableModels.length || 0} models, ${agentData[agent].modes?.availableModes.length || 0} modes`
      );
    } catch (error) {
      console.error(`    ✗ Failed: ${error}`);
      process.exit(1);
    }
  }

  const output = `// Auto-generated by scripts/generate-models.ts
// Run: bun run scripts/generate-models.ts

export const agents = ["claude", "codex"] as const;
export type AgentType = (typeof agents)[number];

export interface ModelInfo {
  modelId: string;
  name: string;
  description?: string;
}

export interface ModeInfo {
  id: string;
  name: string;
  description?: string;
}

export interface AgentConfig {
  models: ModelInfo[];
  defaultModelId: string;
  modes: ModeInfo[];
  defaultModeId: string;
}

export const agentConfigs: Record<AgentType, AgentConfig> = {
  claude: {
    models: ${JSON.stringify(agentData.claude.models?.availableModels || [], null, 4).replace(/\n/g, "\n    ")},
    defaultModelId: ${JSON.stringify(agentData.claude.models?.currentModelId || "default")},
    modes: ${JSON.stringify(agentData.claude.modes?.availableModes || [], null, 4).replace(/\n/g, "\n    ")},
    defaultModeId: ${JSON.stringify(agentData.claude.modes?.currentModeId || "default")},
  },
  codex: {
    models: ${JSON.stringify(agentData.codex.models?.availableModels || [], null, 4).replace(/\n/g, "\n    ")},
    defaultModelId: ${JSON.stringify(agentData.codex.models?.currentModelId || "default")},
    modes: ${JSON.stringify(agentData.codex.modes?.availableModes || [], null, 4).replace(/\n/g, "\n    ")},
    defaultModeId: ${JSON.stringify(agentData.codex.modes?.currentModeId || "default")},
  },
} as const;

// Convenience exports
export const claudeModels = agentConfigs.claude.models;
export const claudeModes = agentConfigs.claude.modes;
export const codexModels = agentConfigs.codex.models;
export const codexModes = agentConfigs.codex.modes;
`;

  const outputPath = new URL("../src/generated/agents.ts", import.meta.url)
    .pathname;
  writeFileSync(outputPath, output);

  console.log(`\n✓ Generated ${outputPath}`);
}

main();
